name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "store = /home/runner/nix"

      - name: Restore from cache
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/nix
          key: key

      - name: Compile LaTeX document
        uses: workflow/nix-shell-action@v3
        with:
          packages: texlive.combined.scheme-full, asymptote
          script: |
            latexmk -pdflatex stirling.tex

      - name: Upload artifcat
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: stirling.pdf
