name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency:
  group: \${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: "store = /home/runner/nix"

      - name: Restore from cache
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/nix
          key: key

      - name: Compile LaTeX document
        uses: workflow/nix-shell-action@v3
        with:
          packages: texlive.combined.scheme-full, asymptote
          script: |
            latexmk -pdflatex stirling.tex

      - name: Get next version
        uses: reecetech/version-increment@2023.4.1
        id: version
        with:
          scheme: semver
          increment: minor

      - name: Create tag name
        if: github.ref == 'refs/heads/main'
        run:  |
          VERSION="prod-$(date -u +'%Y%m%d%H%M%SZ')"
          echo "release_tag=$VERSION" >> $GITHUB_ENV


      - name: Create tag
        if: github.ref == 'refs/heads/main'
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.version }}

      - name: Create Github Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}"
          draft: false
          prerelease: false
          files: stirling.pdf
